import {lab,rc} from './api'

export function Timeline({meta,f,setF,play,setPlay,peaks}){
  const t=meta.frames[f]
  return <div className="p-4 sm:p-5"><div className="flex items-center gap-2 mb-3 flex-wrap"><button className="btn" style={{padding:'8px 18px'}} onClick={()=>setPlay(!play)}>{play?'Pause':'Play forecast'}</button><button className="chip" onClick={()=>{setPlay(false);setF(meta.now)}}>Jump to now</button><button className="chip" onClick={()=>setF(Math.max(0,f-1))}>−15m</button><button className="chip" onClick={()=>setF(Math.min(meta.frames.length-1,f+1))}>+15m</button><h3 className="text-base ml-auto m-0 font-bold" style={{color:t>0?'#b4501b':'var(--blue)'}}>{t>0?'Forecast '+lab(t)+' ahead':t===0?'Latest observation':'Observed '+lab(t)}</h3></div><div className="flex items-end gap-[3px] h-14">{meta.frames.map((m,i)=>{const c=rc(peaks[i]||0);return <button key={i} title={lab(m)+': '+Math.round(peaks[i]||0)+' dBZ'} onClick={()=>{setPlay(false);setF(i)}} className="flex-1 rounded-md border-0 p-0 cursor-pointer" style={{height:Math.max(10,(peaks[i]||0)/70*100)+'%',background:c?`rgb(${c})`:'#cfd9f3',opacity:i<meta.now?.45:1,outline:i===f?'2px solid var(--ink)':'none',outlineOffset:2}}/>})}</div><input type="range" min="0" max={meta.frames.length-1} value={f} onChange={e=>{setPlay(false);setF(+e.target.value)}} className="w-full mt-3" style={{accentColor:'#2f5bff'}} aria-label="Forecast time"/><div className="flex justify-between text-xs" style={{color:'var(--mut)'}}><span>-60 min</span><span>Now</span><span>+90</span><span>+180 min</span></div></div>
}

export function OperationalSummary({fr,alerts}){
  const cities=fr?.cities||[], max=cities.reduce((a,b)=>a.prob>b.prob?a:b,cities[0]);
  return <section className="glass p-5"><div className="flex items-center justify-between mb-3"><h3 className="text-lg m-0">Operational snapshot</h3><span className="tag b">{fr?.t>0?`T+${fr.t} min`:'Latest frame'}</span></div><div className="grid grid-cols-3 gap-2 mb-3"><div className="mini-stat"><b>{cities.filter(c=>c.prob>=.6).length}</b><span>at risk</span></div><div className="mini-stat"><b>{max?Math.round(max.prob*100):0}%</b><span>peak probability</span></div><div className="mini-stat"><b>{fr?.lightning?.length||0}</b><span>strikes</span></div></div><p className="text-[13px] m-0" style={{color:'var(--mut)',lineHeight:1.55}}>{max?`Highest modeled risk in this frame is around ${max.name} at ${Math.round(max.prob*100)}%.`:'Waiting for forecast frame.'} {alerts.length?`${alerts.length} alert zones are identified across the 3-hour horizon.`:'No threshold crossings in the current horizon.'}</p></section>
}

export function Feeds({feeds}){const live=feeds.filter(s=>s.ok).length;return <section className="glass p-5"><div className="flex items-center justify-between mb-3"><h3 className="text-lg m-0">Data feeds</h3><span className="tag g"><span className="live">●</span> {live} of {feeds.length} healthy</span></div><ul className="grid gap-2.5 m-0 p-0 list-none">{feeds.map(s=><li key={s.name} className="flex items-center gap-3 text-[13px]"><span style={{width:9,height:9,borderRadius:9,background:s.ok?'var(--ok)':'var(--cor)',flex:'none'}}/><span className="flex-1 min-w-0"><span className="font-semibold">{s.name}</span><span style={{color:'var(--mut)'}}> {s.kind}, every {s.cadence>=60?s.cadence/60+' h':s.cadence+' min'}</span></span><span className="whitespace-nowrap font-medium" style={{color:s.ok?'var(--mut)':'var(--cor)'}}>{s.ok?s.latency+' min':'Lagging '+s.latency+' min'}</span></li>)}</ul></section>}

const col={Severe:'var(--cor)',Warning:'#d99000',Watch:'var(--blue)'}
export function Alerts({log,sent,send,total,onFocus,onCap,user,filter,setFilter}){return <section className="glass p-5"><div className="flex items-center justify-between gap-2 mb-3 flex-wrap"><h3 className="text-lg m-0">Alert dispatcher</h3><span className="tag b">{total} zones in 3 h</span></div><div className="flex gap-1.5 mb-3">{['All','Severe','Warning','Watch'].map(x=><button key={x} className={'chip '+(filter===x?'on':'')} onClick={()=>setFilter(x)}>{x}</button>)}</div><ul className="grid gap-2.5 m-0 p-0 list-none overflow-auto scr" style={{maxHeight:380}}>{log.length===0&&<li className="text-[13px]" style={{color:'var(--mut)'}}>Waiting for the first alert from the model.</li>}{log.map(e=>{const auto=e.level==='Severe'||sent[e.k];return <li key={e.k} role="button" tabIndex={0} onClick={()=>onFocus(e)} onKeyDown={x=>x.key==='Enter'&&onFocus(e)} title="Fly to the storm cell" className="rounded-2xl p-3.5 text-[13px] cursor-pointer" style={{background:'rgba(255,255,255,.78)',borderLeft:'4px solid '+col[e.level],boxShadow:e.level==='Severe'?'0 0 0 2px rgba(229,72,77,.25)':'none'}}><div className="flex justify-between gap-2"><span className="font-bold" style={{color:col[e.level]}}>{e.level}: {e.city}</span><span style={{color:'var(--mut)'}}>{new Date(e.at*1000).toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata'})}</span></div><div className="mt-1">{e.prob}% chance of thunderstorm and lightning in {e.lead===0?'progress':e.lead+' min'}, peak {e.peak} dBZ.</div><div className="mt-2 flex gap-2 flex-wrap items-center"><button className="chip" onClick={x=>{x.stopPropagation();onCap(e)}}>View CAP XML</button>{auto?<span className="tag g">{e.level==='Severe'&&!sent[e.k]?'Auto-dispatch ready':'Dispatched'}</span>:<button className="chip on" onClick={x=>{x.stopPropagation();send(e.k)}}>Dispatch alert</button>}<span className="text-[11px] ml-auto" style={{color:'var(--mut)'}}>Locate</span></div></li>})}</ul></section>}

export function Skill({skill,t}){const lead=Math.max(0,t),k=[30,60,120,180].reduce((p,c)=>Math.abs(c-lead)<Math.abs(p-lead)?c:p),s=skill&&skill[k];const bar=(n,v)=><div className="flex items-center gap-2 text-xs mb-1.5"><span style={{width:34}} className="font-semibold">{n}</span><span className="flex-1 rounded-full" style={{background:'#e3eafb',height:9}}><span style={{display:'block',height:9,width:Math.min(100,v*100)+'%',background:'var(--blue)',borderRadius:9}}/></span><span style={{width:32,textAlign:'right'}}>{v.toFixed(2)}</span></div>;return <section className="glass p-5"><h3 className="text-lg m-0 mb-2">Model skill</h3><p className="text-[13px] m-0 mb-3" style={{color:'var(--mut)',lineHeight:1.55}}>Holdout performance for the selected forecast lead. These scores are from synthetic storms in the bundled demo and must be recalibrated on operational archives.</p>{s?<><div className="text-xs mb-2 font-semibold">Lead: {k} min</div>{bar('POD',s.pod)}{bar('FAR',s.far)}{bar('CSI',s.csi)}</>:<div className="text-xs">Loading skill scores.</div>}</section>}

export function ModelStatus({health}){return <section className="glass p-5"><div className="flex items-center justify-between"><h3 className="text-lg m-0">Model & provenance</h3><span className="tag g">{health?.model==='satquery'?'SatQuery adapter':'Fallback model'}</span></div><div className="grid gap-2 mt-3 text-[13px]" style={{color:'var(--mut)'}}><div><b style={{color:'var(--ink)'}}>Inference:</b> {health?.model_detail||'Loading…'}</div><div><b style={{color:'var(--ink)'}}>Forecast:</b> 15-minute steps, 0–180 minutes</div><div><b style={{color:'var(--ink)'}}>Safety:</b> human-in-the-loop; alerts are decision support, not a guarantee.</div></div></section>}

export function RiskTable({cities,onFocus}){return <div className="overflow-auto"><table className="risk-table"><thead><tr><th>Location</th><th>Risk</th><th>Probability</th><th>Peak</th><th>Action</th></tr></thead><tbody>{cities.map(c=><tr key={c.name}><td className="font-bold">{c.name}</td><td><span className={'tag '+(c.risk==='Severe'?'p':c.risk==='Warning'?'warn':c.risk==='Watch'?'b':'g')}>{c.risk}</span></td><td><div className="flex items-center gap-2 min-w-[130px]"><div className="risk-bar"><i style={{width:Math.round(c.prob*100)+'%'}}/></div><b>{Math.round(c.prob*100)}%</b></div></td><td>{Math.round(c.prob*65)} dBZ*</td><td><button className="chip" onClick={()=>onFocus(c)}>Locate</button></td></tr>)}</tbody></table><p className="text-[11px] mt-3 mb-0" style={{color:'var(--mut)'}}>*Peak reflectivity in this explorer is a visualized risk proxy for the selected frame; CAP alerts use their forecast peak value.</p></div>}
